# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        series_images:
            uri_prefix: /images/series
            upload_destination: '%kernel.project_dir%/public/images/series'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true